spring:
  application:
    name: backend
  datasource:
    url: jdbc:mysql://localhost:3307/defesa-civil?useSSL=false&serverTimezone=UTC
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL8Dialect
#    show-sql: true

jwt:
  public:
    key: classpath:authz.pub
  private:
    key: classpath:authz.pem
